<?php

namespace App\Support\Prompt;

/**
 * Backstory archetype engine: regex tests against the backstory (and physical
 * description) that boost wardrobe tags, infer a build hint, add a physical
 * marker, pick a scene niche, and optionally lock a specific scene.
 */
final class BackstoryArchetypes
{
    public const ENTRIES = [
        // ── FITNESS ─────────────────────────────────────────────────
        [
            'test' => '/yoga.?instructor|yoga.?teacher|yoga.?coach/',
            'tags' => ['sport', 'natural', 'earthy', 'bohemian'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean, flexible, long-limbed',
            'physicalDetail' => null,
            'lockedScene' => 'yoga studio, pale wood floor, floor-to-ceiling mirror wall, soft diffused morning light through large windows',
        ],
        [
            'test' => '/pilates.?instructor|pilates.?teacher|reformer/',
            'tags' => ['sport', 'clean', 'natural'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean, toned, precise upright posture',
            'physicalDetail' => null,
            'lockedScene' => 'pilates studio, reformer machines visible soft in background, clean bright space with natural light',
        ],
        [
            'test' => '/crossfit|hiit.?coach|functional.?fitness/',
            'tags' => ['sport', 'functional', 'casual'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'muscular, functional build',
            'physicalDetail' => null,
            'lockedScene' => 'crossfit box, pull-up rigs and bumper plates visible soft behind, industrial ceiling and rubber flooring',
        ],
        [
            'test' => '/personal.?trainer|fitness.?coach|strength.?coach|gym.?owner|gym.?instructor/',
            'tags' => ['sport', 'functional', 'casual'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'athletic, visibly fit',
            'physicalDetail' => null,
            'lockedScene' => 'minimalist gym interior, rubber floor, weight racks and barbells visible soft in background, large windows letting in hard morning side-light from camera-left',
        ],
        [
            'test' => '/nutritionist|dietitian|sports.?nutritionist/',
            'tags' => ['sport', 'earthy', 'natural'],
            'sceneNiche' => 'fitness',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/marathon|ultra.?runner|long.?distance.?runner/',
            'tags' => ['sport', 'earthy', 'functional'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean endurance build',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\brunner\b|running.?coach|track.?athlete/',
            'tags' => ['sport', 'functional', 'casual'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean runner\'s build',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/cyclist|road.?bike|mountain.?bik/',
            'tags' => ['sport', 'functional'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean, powerful legs',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bswimmer\b|swimming|open.?water/',
            'tags' => ['sport', 'coastal', 'natural'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'broad-shouldered, lean swimmer\'s build',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bsurfer\b|surfing|surf.?instructor/',
            'tags' => ['coastal', 'natural', 'casual', 'earthy'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean, sun-bronzed',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/dancer|dance.?teacher|choreographer|ballet|contemporary.?dance/',
            'tags' => ['editorial', 'bold', 'sport'],
            'sceneNiche' => 'entertainment',
            'buildHint' => 'lean, long-limbed, precise upright posture',
            'physicalDetail' => null,
            'lockedScene' => 'dance studio, sprung wood floor, floor-to-ceiling mirror, barre visible in background',
        ],
        [
            'test' => '/martial.?art|mma|boxing|kickboxing|judo|jiu.?jitsu|muay.?thai/',
            'tags' => ['sport', 'dark', 'functional'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean, compact, coiled',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/gymnast|gymnastics/',
            'tags' => ['sport', 'functional', 'editorial'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'compact, powerfully built',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/meditation.?teacher|mindfulness.?coach|breathwork/',
            'tags' => ['earthy', 'natural', 'bohemian'],
            'sceneNiche' => 'fitness',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/life.?coach|wellness.?coach|holistic.?health|health.?coach/',
            'tags' => ['natural', 'clean', 'earthy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/professional.?athlete|pro.?athlete|olympic|national.?team/',
            'tags' => ['sport', 'functional'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'peak athletic build',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bcoach\b|sports.?coach|athletic.?director/',
            'tags' => ['sport', 'casual', 'functional'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'fit, athletic',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bgym\b|weightlifting|powerlifting|bodybuilding/',
            'tags' => ['sport', 'functional', 'casual'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'visibly muscular, powerful frame',
            'physicalDetail' => null,
            'lockedScene' => 'gym interior, squat rack and plates visible soft behind, rubber floor, industrial ceiling with high strip lighting',
        ],
        [
            'test' => '/tennis|padel/',
            'tags' => ['preppy', 'sport', 'clean'],
            'sceneNiche' => 'fitness',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bgolfer\b|\bgolf\b/',
            'tags' => ['old-money', 'preppy', 'sport'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/basketball|nba\b/',
            'tags' => ['street', 'sport', 'casual'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'tall, athletic',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/football|soccer|footballer|pitch/',
            'tags' => ['sport', 'casual', 'street'],
            'sceneNiche' => 'fitness',
            'buildHint' => 'lean, athletic',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bskater\b|skateboarding/',
            'tags' => ['street', 'y2k', 'casual'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/snowboarder|snowboarding|skiing|\bskier\b/',
            'tags' => ['casual', 'earthy', 'sport'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/rock.?climber|climbing|bouldering/',
            'tags' => ['earthy', 'functional', 'casual'],
            'sceneNiche' => 'travel',
            'buildHint' => 'lean, wiry and strong',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bhiker\b|hiking|trekker/',
            'tags' => ['earthy', 'functional', 'natural'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],

        // ── FOOD & HOSPITALITY ──────────────────────────────────────
        [
            'test' => '/executive.?chef|head.?chef|michelin|fine.?dining/',
            'tags' => ['editorial', 'structured', 'polished'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'outside a restaurant entrance, warm kitchen light spilling through the open door behind, city street at dusk',
        ],
        [
            'test' => '/pastry.?chef|patisserie/',
            'tags' => ['cottagecore', 'earthy', 'natural'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'bakery counter or café window, warm morning light, pastries visible soft in background',
        ],
        [
            'test' => '/\bbaker\b|baking|sourdough/',
            'tags' => ['cottagecore', 'earthy', 'natural'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'bakery counter or café window, warm morning light, bread and pastries soft in background',
        ],
        [
            'test' => '/\bchef\b|culinary|kitchen|cook\b/',
            'tags' => ['casual', 'earthy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'outside a restaurant or street-food stall, warm ambient evening light, kitchen noise implied behind',
        ],
        [
            'test' => '/barista|coffee.?roaster|café.?owner/',
            'tags' => ['casual', 'minimalist', 'clean'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'beside a café counter, espresso machine gleaming soft behind, warm amber overhead light',
        ],
        [
            'test' => '/bartender|mixologist|bar.?owner/',
            'tags' => ['dark', 'casual', 'glam'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'bar or venue interior, warm practicals above, moody ambient light, bottles soft in background',
        ],
        [
            'test' => '/sommelier|\bwine\b|winery|vineyard/',
            'tags' => ['old-money', 'polished', 'earthy'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/food.?blogger|food.?photographer|food.?stylist/',
            'tags' => ['casual', 'earthy', 'lifestyle'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/restaurant.?owner|restaurateur/',
            'tags' => ['polished', 'editorial', 'casual'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'inside or outside their restaurant, warm ambient lighting, tables soft in background',
        ],

        // ── FASHION & BEAUTY ────────────────────────────────────────
        [
            'test' => '/\bmodel\b|fashion.?model|runway|catwalk/',
            'tags' => ['editorial', 'structured', 'polished'],
            'sceneNiche' => 'fashion',
            'buildHint' => 'tall, lean, long-limbed',
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/fashion.?designer|clothing.?designer/',
            'tags' => ['editorial', 'bold', 'structured'],
            'sceneNiche' => 'fashion',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bstylist\b|fashion.?stylist|wardrobe.?stylist|personal.?stylist/',
            'tags' => ['editorial', 'minimalist', 'structured'],
            'sceneNiche' => 'fashion',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/fashion.?blogger|fashion.?persona/',
            'tags' => ['editorial', 'bold'],
            'sceneNiche' => 'fashion',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/makeup.?artist|mua\b|beauty.?artist/',
            'tags' => ['glam', 'editorial', 'clean'],
            'sceneNiche' => 'beauty',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/hairdresser|hair.?stylist|hair.?colorist/',
            'tags' => ['casual', 'editorial', 'clean'],
            'sceneNiche' => 'beauty',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'salon interior, styling chairs visible soft in background, bright salon lighting',
        ],
        [
            'test' => '/nail.?artist|nail.?technician/',
            'tags' => ['playful', 'bold', 'clean'],
            'sceneNiche' => 'beauty',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/beauty.?blogger|beauty.?persona/',
            'tags' => ['glam', 'clean', 'natural'],
            'sceneNiche' => 'beauty',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/esthetician|skincare.?specialist|facialist/',
            'tags' => ['clean', 'natural', 'minimalist'],
            'sceneNiche' => 'beauty',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/creative.?director|art.?director/',
            'tags' => ['editorial', 'structured', 'bold'],
            'sceneNiche' => 'fashion',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],

        // ── TECH & BUSINESS ─────────────────────────────────────────
        [
            'test' => '/software.?engineer|developer|programmer|coder|full.?stack|backend|frontend/',
            'tags' => ['minimalist', 'quiet', 'clean'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'minimal home desk or co-working space, large monitor soft in background, window light from one side',
        ],
        [
            'test' => '/startup.?founder|tech.?founder/',
            'tags' => ['minimalist', 'structured', 'editorial'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'modern co-working space, city view through full-height glass behind',
        ],
        [
            'test' => '/\bceo\b|\bcoo\b|\bcto\b|c-suite/',
            'tags' => ['old-money', 'structured', 'polished'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'city office, floor-to-ceiling glass windows, urban skyline visible soft behind',
        ],
        [
            'test' => '/entrepreneur|business.?owner|self.?employed|founder/',
            'tags' => ['minimalist', 'casual', 'structured'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/ux.?designer|product.?designer|ui.?designer/',
            'tags' => ['minimalist', 'clean', 'editorial'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/product.?manager|\bpm\b/',
            'tags' => ['minimalist', 'clean', 'preppy'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/crypto|blockchain|web3|\bnft\b|\bdefi\b/',
            'tags' => ['street', 'y2k', 'casual'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/real.?estate|property.?developer|realtor/',
            'tags' => ['polished', 'preppy', 'old-money'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/financial.?advisor|wealth.?manager|portfolio.?manager/',
            'tags' => ['old-money', 'polished', 'preppy'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bbanker\b|investment.?bank|private.?equity|hedge.?fund/',
            'tags' => ['old-money', 'structured', 'polished'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/day.?trader|\btrader\b|stock.?market/',
            'tags' => ['minimalist', 'casual'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\blawyer\b|attorney|solicitor|barrister/',
            'tags' => ['old-money', 'structured', 'editorial'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'steps of a courthouse or law office building exterior, clean stone steps, city behind',
        ],

        // ── CREATIVE ────────────────────────────────────────────────
        [
            'test' => '/\bphotographer\b|photography/',
            'tags' => ['editorial', 'minimalist', 'casual'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/videographer|cinematographer/',
            'tags' => ['editorial', 'casual', 'dark'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/filmmaker|film.?director|\bdirector\b/',
            'tags' => ['editorial', 'dark', 'structured'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/graphic.?designer|illustrator/',
            'tags' => ['editorial', 'minimalist', 'casual'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/interior.?designer|interior.?decorator/',
            'tags' => ['minimalist', 'editorial', 'old-money'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bartist\b|painter|sculptor|fine.?art/',
            'tags' => ['bohemian', 'editorial', 'earthy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'artist\'s studio, canvases or artworks visible soft behind, north-facing window light',
        ],
        [
            'test' => '/\bmusician\b|\bsinger\b|vocalist|recording.?artist/',
            'tags' => ['dark', 'bohemian', 'editorial'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'recording studio corner, microphone stand or mixing board soft behind, warm practical lighting',
        ],
        [
            'test' => '/\bdj\b|music.?producer|producer\b/',
            'tags' => ['street', 'dark', 'casual'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'behind a DJ booth or in a studio, equipment visible soft behind, moody low ambient light',
        ],
        [
            'test' => '/\brapper\b|hip.?hop|\bmc\b/',
            'tags' => ['street', 'dark', 'bold'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bactor\b|\bactress\b|performer|theatre/',
            'tags' => ['editorial', 'glam', 'casual'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bcomedian\b|stand.?up|comedy.?writer/',
            'tags' => ['casual', 'street', 'y2k'],
            'sceneNiche' => 'entertainment',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bwriter\b|\bauthor\b|novelist|screenwriter/',
            'tags' => ['quiet', 'minimalist', 'earthy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'café corner, open notebook or laptop soft on table, afternoon window light',
        ],
        [
            'test' => '/podcaster|podcast.?host/',
            'tags' => ['casual', 'minimalist'],
            'sceneNiche' => 'tech',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'podcast desk setup, microphone visible in foreground or soft behind, acoustic panels or bookshelf in background',
        ],
        [
            'test' => '/journalist|reporter|correspondent/',
            'tags' => ['casual', 'minimalist', 'preppy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/youtuber|youtube.?creator|\bvlogg|\bvlog\b/',
            'tags' => ['casual', 'y2k', 'street'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/tiktoker|tiktok.?creator/',
            'tags' => ['y2k', 'casual', 'playful'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/streamer|twitch|gaming.?content/',
            'tags' => ['casual', 'street'],
            'sceneNiche' => 'gaming',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'gaming setup visible behind, RGB lighting as background ambient, one window as key light',
        ],
        [
            'test' => '/\bblogger\b|content.?creator/',
            'tags' => ['casual', 'lifestyle'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],

        // ── HEALTH ──────────────────────────────────────────────────
        [
            'test' => '/pharmacist|pharmacy/',
            'tags' => ['clean', 'minimalist', 'preppy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => 'thin wire-frame glasses',
            'lockedScene' => 'pharmacy counter or clinic corridor, clean institutional light, shelves soft in background',
        ],
        [
            'test' => '/\bdoctor\b|\bphysician\b|\bmd\b/',
            'tags' => ['clean', 'minimalist', 'preppy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => 'thin wire-frame glasses',
            'lockedScene' => 'clinic consultation room, clean desk and framed qualifications soft on the wall behind, diffused overhead light',
        ],
        [
            'test' => '/\bnurse\b|nursing|registered.?nurse/',
            'tags' => ['clean', 'casual', 'minimalist'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'hospital corridor, clean white walls, soft institutional overhead light',
        ],
        [
            'test' => '/therapist|psychologist|counsellor|mental.?health/',
            'tags' => ['quiet', 'minimalist', 'earthy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => 'calm therapy office, a comfortable armchair and soft lamp visible in background, warm quiet light',
        ],
        [
            'test' => '/acupuncturist|chiropractor|physiotherapist|physical.?therapist/',
            'tags' => ['earthy', 'natural', 'clean'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],

        // ── EDUCATION ───────────────────────────────────────────────
        [
            'test' => '/\bstudent\b|college|university|grad.?student/',
            'tags' => ['casual', 'street', 'preppy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bprofessor\b|\blecturer\b|academic/',
            'tags' => ['preppy', 'old-money', 'minimalist'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => 'wire-frame glasses',
            'lockedScene' => 'university library or faculty corridor, bookshelves soft in background, warm institutional light',
        ],
        [
            'test' => '/\bteacher\b|educator/',
            'tags' => ['casual', 'preppy', 'clean'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],

        // ── TRAVEL & LIFESTYLE ──────────────────────────────────────
        [
            'test' => '/travel.?blogger|travel.?persona|travel.?creator|travel.?vlog|\btravell?ing\b/',
            'tags' => ['bohemian', 'casual', 'coastal'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/digital.?nomad/',
            'tags' => ['casual', 'bohemian', 'minimalist'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bexpat\b|living.?abroad/',
            'tags' => ['bohemian', 'casual', 'coastal'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],

        // ── VALUES & LIFESTYLE ──────────────────────────────────────
        [
            'test' => '/dog.?owner|dog.?lover|pet.?parent|dog.?mom|dog.?dad/',
            'tags' => ['casual', 'earthy', 'natural'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/new.?mom|\bnew mom\b|new.?parent|postpartum/',
            'tags' => ['casual', 'clean', 'natural'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/sustainable|eco.?friendly|environmentalist/',
            'tags' => ['earthy', 'natural', 'bohemian'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/spiritual|mindfulness|meditation|buddhist/',
            'tags' => ['earthy', 'bohemian', 'natural'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/activist|advocate|social.?justice|community.?organizer/',
            'tags' => ['street', 'casual', 'earthy'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/luxury|high.?end|yacht|penthouse/',
            'tags' => ['old-money', 'glam', 'polished'],
            'sceneNiche' => 'travel',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bfreelance\b|freelancer/',
            'tags' => ['casual', 'minimalist'],
            'sceneNiche' => 'lifestyle',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],

        // ── AESTHETICS (catch-all style signals) ────────────────────
        [
            'test' => '/old.?money|heritage|generational|ivy.?league|equestrian|boarding.?school|country.?club|prep.?school/',
            'tags' => ['old-money', 'classic', 'polished', 'quiet'],
            'sceneNiche' => null,
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/designer|couture|high.?fashion|fashion.?week|rick owens|the row|bottega|celine|loewe/',
            'tags' => ['polished', 'editorial', 'structured', 'old-money'],
            'sceneNiche' => 'fashion',
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/street|urban|downtown|brooklyn|graffiti/',
            'tags' => ['street', 'urban', 'casual'],
            'sceneNiche' => null,
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/\bminimalist\b|\bminimal\b|understated|quiet.?aesthetic|\bquiet\b|\breserved\b|\bintroverted\b/',
            'tags' => ['minimalist', 'quiet', 'clean'],
            'sceneNiche' => null,
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/boho|bohemian|free.?spirit|wanderer|earthy/',
            'tags' => ['bohemian', 'earthy', 'natural'],
            'sceneNiche' => null,
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/dark.?aesthetic|gothic|moody|alternative|grunge/',
            'tags' => ['dark', 'moody', 'urban'],
            'sceneNiche' => null,
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
        [
            'test' => '/glam|glamour|sequin|evening.?wear|gala|black.?tie|cocktail/',
            'tags' => ['glam', 'evening', 'bold'],
            'sceneNiche' => null,
            'buildHint' => null,
            'physicalDetail' => null,
            'lockedScene' => null,
        ],
    ];

    /**
     * Return the first archetype whose test regex matches the given backstory,
     * or null when nothing matches.
     */
    public static function match(string $backstory): ?array
    {
        foreach (self::ENTRIES as $entry) {
            if (@preg_match($entry['test'], $backstory)) {
                return $entry;
            }
        }

        return null;
    }
}
